-- database: ../dataBase/ExaBot2k24.sqlite

DROP TABLE IF EXISTS EXABOT;

DROP TABLE IF EXISTS IABOT;

DROP TABLE IF EXISTS PERSONA;

DROP TABLE IF EXISTS PERSONATIPO;

CREATE TABLE IABOT (
    IDIABOT INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    OBSERVACION TEXT,
    ESTADO VARCHAR(1) DEFAULT('A') CHECK (ESTADO IN ('A', 'X')),
    FECHACREA DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EXABOT (
    IDEXABOT INTEGER PRIMARY KEY AUTOINCREMENT,
    IDIABOT INTEGER NOT NULL,
    NOMBRE TEXT NOT NULL,
    SERIE TEXT NOT NULL,
    ESTADO VARCHAR(1) DEFAULT('A') CHECK (ESTADO IN ('A', 'X')),
    FECHACREA DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_IABOT_EXABOT FOREIGN KEY (IDIABOT) REFERENCES IABOT(IDIABOT)
);

CREATE TABLE PERSONATIPO (
    IDPERSONATIPO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL UNIQUE,
    ESTADO VARCHAR(1) DEFAULT('A') CHECK (ESTADO IN ('A', 'X')),
    FECHACREA DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PERSONA (
    IDPERSONA INTEGER PRIMARY KEY AUTOINCREMENT,
    IDPERSONATIPO INTEGER NOT NULL REFERENCES PERSONATIPO(IDPERSONATIPO),
    CEDULA VARCHAR(10) NOT NULL UNIQUE,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(1) DEFAULT('A') CHECK (ESTADO IN ('A', 'X')),
    FECHACREA DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SEXO (
    IdSexo INTEGER PRIMARY KEY AUTOINCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(1) DEFAULT('A') CHECK (ESTADO IN ('A', 'X')),
    FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    FechaModificacion DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO SEXO(Nombre)
VALUES("Femenino")