-- database: ../dataBase/ExaBot2k24.sqlite
DROP TABLE IF EXISTS PERSONA;

DROP TABLE IF EXISTS EXABOT;

DROP TABLE IF EXISTS CATALOGO;

DROP TABLE IF EXISTS CATALOGOTIPO;

DROP TABLE IF EXISTS IABOT;

DROP TABLE IF EXISTS SEXO;

/*DROP TABLE IF EXISTS PERSONATIPO;*/
CREATE TABLE
    CATALOGOTIPO (
        IDCATALOGOTIPO INTEGER PRIMARY KEY AUTOINCREMENT,
        NOMBRE VARCHAR(50) NOT NULL UNIQUE,
        DESCRIPCION VARCHAR(90) NOT NULL,
        ESTADO VARCHAR(1) DEFAULT ('A') CHECK (ESTADO IN ('A', 'X')),
        FECHACREA DATETIME DEFAULT (DATETIME('now', 'localtime'))
    );

-- database: ../dataBase/ExaBot2k24.sqlite
CREATE TABLE
    CATALOGO (
        IDCATALOGO INTEGER PRIMARY KEY AUTOINCREMENT,
        IDCATALOGOTIPO INTEGER NOT NULL REFERENCES CATALOGOTIPO (IDCATALOGOTIPO),
        NOMBRE VARCHAR(50) NOT NULL UNIQUE,
        DESCRIPCION VARCHAR(90) NOT NULL,
        ESTADO VARCHAR(1) DEFAULT ('A') CHECK (ESTADO IN ('A', 'X')),
        FECHACREA DATETIME DEFAULT (DATETIME('now', 'localtime'))
    );

CREATE TABLE
    IABOT (
        IDIABOT INTEGER PRIMARY KEY AUTOINCREMENT,
        NOMBRE VARCHAR(50) NOT NULL UNIQUE,
        OBSERVACION VARCHAR(50) NOT NULL,
        ESTADO VARCHAR(1) DEFAULT ('A') CHECK (ESTADO IN ('A', 'X')),
        FECHACREA DATETIME DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    EXABOT (
        IDEXABOT INTEGER PRIMARY KEY AUTOINCREMENT,
        IDIABOT INTEGER NOT NULL,
        NOMBRE TEXT NOT NULL,
        SERIE TEXT NOT NULL,
        ESTADO VARCHAR(1) DEFAULT ('A') CHECK (ESTADO IN ('A', 'X')),
        FECHACREA DATETIME DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT FK_IABOT_EXABOT FOREIGN KEY (IDIABOT) REFERENCES IABOT (IDIABOT)
    );

/* CREATE TABLE PERSONATIPO (
IDPERSONATIPO INTEGER PRIMARY KEY AUTOINCREMENT,
NOMBRE TEXT NOT NULL UNIQUE,
ESTADO VARCHAR(1) DEFAULT('A') CHECK (ESTADO IN ('A', 'X')),
FECHACREA DATETIME DEFAULT CURRENT_TIMESTAMP
); */
CREATE TABLE
    PERSONA (
        IDPERSONA INTEGER PRIMARY KEY AUTOINCREMENT,
        IDCATALOGOTIPOPERSONA INTEGER NOT NULL REFERENCES CATALOGO (IDCATALOGO),
        IDCATALOGOSEXO INTEGER NOT NULL REFERENCES CATALOGO (IDCATALOGO),
        IDCATALOGOESTADOCIVIL INTEGER NOT NULL REFERENCES CATALOGO (IDCATALOGO),
        CEDULA VARCHAR(10) NOT NULL UNIQUE,
        NOMBRE VARCHAR(50) NOT NULL,
        APELLIDO VARCHAR(50) NOT NULL,
        ESTADO VARCHAR(1) DEFAULT ('A') CHECK (ESTADO IN ('A', 'X')),
        FECHACREA DATETIME DEFAULT (DATETIME('now', 'localtime'))
    );

CREATE TABLE
    SEXO (
        IDSEXO INTEGER PRIMARY KEY AUTOINCREMENT,
        NOMBRE VARCHAR(50) NOT NULL,
        ESTADO VARCHAR(1) DEFAULT ('A') CHECK (ESTADO IN ('A', 'X')),
        FECHACREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
        FECHAMODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP
    );
